version: '3'
services:
  db:
    image: mysql:8.0
    environment:
      - MYSQL_ROOT_PASSWORD=Oratoroeu@01
      - MYSQL_DATABASE=firma_colaboradores
      - MYSQL_USER=Reideroma
      - MYSQL_PASSWORD=Oratoroeu@01
    ports:
      - "3307:3306"
    volumes:
      - ./mysql-data:/var/lib/mysql

  app:
    build: .
    ports:
      - "8081:8081
      "
    depends_on:
      - db
    environment:
      - SPRING_DATASOURCE_URL=jdbc:mysql://db:3306/firma_colaboradores
      - SPRING_DATASOURCE_USERNAME=root
      - SPRING_DATASOURCE_PASSWORD=Oratoroeu@01



